/* Generated By:JavaCC: Do not edit this line. lexicalConstants.java */
package Lexical;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface lexicalConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int ELSE = 6;
  /** RegularExpression Id. */
  int INT = 7;
  /** RegularExpression Id. */
  int RETURN = 8;
  /** RegularExpression Id. */
  int VOID = 9;
  /** RegularExpression Id. */
  int WNILE = 10;
  /** RegularExpression Id. */
  int MAIN = 11;
  /** RegularExpression Id. */
  int IDENTIFIER = 12;
  /** RegularExpression Id. */
  int LETTER = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int PLUS = 15;
  /** RegularExpression Id. */
  int MINUS = 16;
  /** RegularExpression Id. */
  int MULTIPLY = 17;
  /** RegularExpression Id. */
  int DIVIDE = 18;
  /** RegularExpression Id. */
  int DY = 19;
  /** RegularExpression Id. */
  int XY = 20;
  /** RegularExpression Id. */
  int BD = 21;
  /** RegularExpression Id. */
  int EQUAL = 22;
  /** RegularExpression Id. */
  int FH = 23;
  /** RegularExpression Id. */
  int DH = 24;
  /** RegularExpression Id. */
  int DZKH = 25;
  /** RegularExpression Id. */
  int DYKH = 26;
  /** RegularExpression Id. */
  int ZZKH = 27;
  /** RegularExpression Id. */
  int ZYKH = 28;
  /** RegularExpression Id. */
  int XZKH = 29;
  /** RegularExpression Id. */
  int XYKH = 30;
  /** RegularExpression Id. */
  int CONSTANT = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"if\"",
    "\"else\"",
    "\"int\"",
    "\"return\"",
    "\"void\"",
    "\"while\"",
    "\"main\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "<CONSTANT>",
  };

}
